### ISSUE TITLE
Publish on GithubPages

### ISSUE THREAD

**Issue by IOAyman** [Mouttahid/texttospeech#1]
It would be cool to push a `gh-pages` branch so a demo of your page would be accessible on [mouttahid.github.io/texttospeech](https://mouttahid.github.io/texttospeech).

---
Docs: https://help.github.com/en/categories/github-pages-basics

**Comment by Mouttahid** [comment]
done , thanks bro.
after 1 year xD
https://github.com/Mouttahid/texttospeech
